version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      actions:
        patterns:
          - '*'
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore(actions)"
      include: "scope"