---
package:
  name: flyway
  version: 11.8.2
  epoch: 0
  description: Flyway database migration tool
  copyright:
    - license: Apache-2.0

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/os
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - busybox
      - ca-certificates-bundle
      - openjdk-17-jre

pipeline:
  - uses: fetch
    with:
      uri: https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/${{package.version}}/flyway-commandline-${{package.version}}.tar.gz
      expected-sha256: b01677117b6be97e669314cc502da85bdce20b426bafc291738368ab980c8ca5

  - name: Install Flyway
    runs: |
      set -e
      FLYWAY_VERSION="${{package.version}}"
      
      # Extract Flyway (archive contains flyway-X.Y.Z/ directory)
      tar -xzf "flyway-commandline-${FLYWAY_VERSION}.tar.gz"
      
      # Move extracted directory to versioned location
      mkdir -p "${{targets.destdir}}/opt"
      mv "flyway-${FLYWAY_VERSION}" "${{targets.destdir}}/opt/flyway-${FLYWAY_VERSION}"
      
      # Make flyway executable
      chmod +x "${{targets.destdir}}/opt/flyway-${FLYWAY_VERSION}/flyway"
      
      # Create generic symlink for easier version management
      ln -s "/opt/flyway-${FLYWAY_VERSION}" "${{targets.destdir}}/opt/flyway"
      
      # Create symlink in /usr/local/bin for global access
      mkdir -p "${{targets.destdir}}/usr/local/bin"
      ln -s "/opt/flyway-${FLYWAY_VERSION}/flyway" \
        "${{targets.destdir}}/usr/local/bin/flyway"

test:
  pipeline:
    - runs: |
        flyway --version

update:
  enabled: true
  github:
    identifier: flyway/flyway
    strip-prefix: flyway-
    tag-filter-prefix: flyway-
