---

name: Create and publish a container image

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    # run every Monday at 01:30
    - cron: '30 1 * * 1'

# Defines two custom environment variables for the workflow. These are used for
# the Container registry domain, and a name for the Docker image that this
# workflow builds.
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

# There is a single job in this workflow. It's configured to run on the latest
# available version of Ubuntu.
jobs:
  wolfi-renovate-nodejs-bash-git-flux:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.BOT_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.BOT_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      # https://github.com/chainguard-images/actions/tree/main/apko-publish
      - id: wolfi-renovate-nodejs-bash-git-flux
        uses: distroless/actions/apko-publish@main
        with:
          config: wolfi-renovate-nodejs-bash-git-flux.yaml
          tag: ghcr.io/duyne-me/wolfi-renovate-nodejs-bash-git-flux:latest

  wolfi-apko-with-bash:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      # https://github.com/chainguard-images/actions/tree/main/apko-publish
      - id: wolfi-apko-with-bash
        uses: distroless/actions/apko-publish@main
        with:
          config: wolfi-apko-with-bash.yaml
          tag: ghcr.io/duyne-me/wolfi-apko-with-bash:latest

  wolfi-renovate-tini-git-flux:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      # https://github.com/chainguard-images/actions/tree/main/apko-publish
      - id: wolfi-renovate-tini-git-flux
        uses: distroless/actions/apko-publish@main
        with:
          config: wolfi-docker-dind.yaml
          # Tag is the tag that will be published.
          # Required.
          tag: ghcr.io/duyne-me/wolfi-docker-dind:latest

  wolfi-bash-aws-cli:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - id: wolfi-bash-aws-cli
        uses: distroless/actions/apko-publish@main
        with:
          config: wolfi-bash-aws-cli.yaml
          # Tag is the tag that will be published.
          # Required.
          tag: ghcr.io/duyne-me/wolfi-bash-aws-cli:latest

  wolfi-bash-kubectl:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - id: wolfi-bash-kubectl
        uses: distroless/actions/apko-publish@main
        with:
          config: wolfi-bash-kubectl.yaml
          # Tag is the tag that will be published.
          # Required.
          tag: ghcr.io/duyne-me/wolfi-bash-kubectl:latest





          